PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sch: <http://schema.org/>

CONSTRUCT{
  ?bookURI a sch:Book;
    sch:identifier ?Book_Id;
    sch:name ?Title;
    sch:creator ?Author;
    sch:isbn: ?ISBN13;
    sch:aggregateRating ?mark;
    sch:publisher ?Publisher;
    sch:numberOfPages ?nbPages;
    sch:datePublished ?Year_Published.
}
FROM <file:goodreads_library_export.csv>
WHERE{
  BIND(URI(CONCAT('https://www.goodreads.com/book/show/',?Book_Id,'-',REPLACE(LCASE(?titre), " ", "-")) AS ?bookURI))
  BIND(xsd:integer(?Number_of_Pages) AS ?nbPages)
  BIND(xsd:decimal(?Average_Rating) AS ?mark)
}
