PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sch: <http://schema.org/>

CONSTRUCT{
  ?bookURI a sch:Book;
    sch:identifier ?Book_Id;
    sch:name ?Title;
    sch:creator ?Author;
    sch:isbn ?ISBN13;
    sch:publisher ?Publisher;
    sch:numberOfPages ?nbPages;
    sch:datePublished ?Year_Published;
    sch:aggregateRating ?aRating.
  ?aRating sch:ratingValue ?AverageRating.
}
WHERE{
  BIND(URI(CONCAT('http://www.goodreads.com/book/show/', (CONCAT(?Book_Id, (CONCAT("-",REPLACE(LCASE(?Title), " ", "-"))))))) AS ?bookURI)
  BIND(xsd:integer(?Number_of_Pages) AS ?nbPages)
}
